server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: qq331173500
    driver-class-name: com.mysql.jdbc.Driver

#  cloud:
#    nacos:
#      server-addr: localhost:80
#      discovery:
#        cluster-name: WX
#        namespace: aca69c37-a135-43bb-9aec-634c12fb2419
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9080/eureka
#
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#ribbon:
#  eager-load:
#    enabled: true
#    clients: userservice

# feign log: all
#feign:
#  client:
#    config:
#      default:
#        logger-level: full

# feign log: single
#feign:
#  client:
#    config:
#      userservice:
#        logger-level: full
feign:
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    enabled: true
